### ISSUE TITLE
Add refiner recipes

### ISSUE THREAD

**Issue by cliffrowley** [nphyx/nms-data#1]
Hey there, I've been tinkering with my own NMS related bits and pieces and discovered your project along the way. There's not much overlap between your project and mine at the moment (which isn't public yet nor a separate project in its own right) and mine is focused primarily on refiner recipes, which I note are absent from this project. Do you plan on adding them at some point?

Also, side-but-related-question: are you using a separate tool to extract this data from the game to generate these files, or are you actually updating them by hand? At some point I'll likely extend my little project to include more data and may end up using this one, and contributing recipes if they aren't already there by that time, and it'd be handy to know what your process is.

**Comment by nphyx** [comment]
I do! They're already up on the NEXT branch: https://github.com/nphyx/nms-data/tree/next I'll be merging to master as soon as I finish updating the rest of the data for 1.5x, but the branch is usable in the meanwhile. I'm still missing some of the refiner recipes. In particular I think some of the alloys are missing and I don't have much data on large refiners. Besides that I still need a list of the new "weird" planet biomes and weathers and I need to get tech & base blueprints written.

Unfortunately it's mostly manual entry from other sources. I've been pulling it from the game guide, wikis, spreadsheets, and reddit posts as needed.

**Comment by cliffrowley** [comment]
Ah nice, I hadn't spotted that. I had a look, and the data isn't actually quite what I need (the data I extracted for my own purposes obviously has the same labels and descriptions etc as the game). I wondered though, are you using this in another project? I'm just curious on the rationale really :)

**Comment by nphyx** [comment]
Yeah I wouldn't mind having the data match the game data, if it was still easy to work with. I mostly play on the PS4 and haven't messed with trying to extract things directly from game data. Just got a new PC that is actually viable for playing the game so I might try to tackle that job at some point.

I do have a script somewhere that extracts discovery info from save files that I may eventually incorporate, but I had to get the data second-hand from PC players when I made it.

This is for use in another project. I extracted this from it because it was becoming a project in its own right and I thought it'd be easier to use as a module. I have some other projects on the "ideas" list that might make use of it as well.

The idea of the main project is to build a shared, searchable discovery database, so this library is mainly for providing labels and validation in the UI, and so you can do things like "find all the known systems in my current region where I can get the raw materials to build a Stasis Device" or "show me all the systems nearby that have haulers with C-wings" or whatever. Obviously most useful in civilized space where lots of documentation is available - I live in Galactic Hub space and am hoping to tie in with the GHub wiki and/or get players to contribute directly. 

The other project isn't usable yet so it's in a private repo, but I'll make it public once it's in a working state.

**Comment by cliffrowley** [comment]
Interesting. My project is in a similar state, in that it's not ready for public consumption - but when it is I'll pop you a link and you can see if anything in there is useful to you. I'll very likely split off the part that extracts the data from the part that consumes it, and at that point I can either release it as-is or we can talk about potentially incorporating some of it here (if that's what you'd want to do, I'm easy really).

**Comment by nphyx** [comment]
For sure, I think a shared data module would be mutually useful to anyone building apps like this.
